# Generated by Django 2.2.10 on 2020-04-26 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaBot', '0002_basket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('number_order', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='№ Заказа')),
                ('user_order', models.TextField(verbose_name='Заказ пользователя с его данными')),
            ],
        ),
    ]
