# Generated by Django 2.2.10 on 2020-04-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teaBot', '0003_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='basket_sum',
        ),
        migrations.RemoveField(
            model_name='users',
            name='time_delivery',
        ),
        migrations.AlterField(
            model_name='allmenu',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Название товара'),
        ),
    ]
